baseURL = "https://matteotomasini.com"
languageCode = "en-us"
pagination.pagerSize = 6
theme = "mattetom"
title = "Matteo Tomasini"
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Blog"
url = "blog"
weight = 3
[[menu.sitemap]]
name = "Contact me"
url = "contact"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © matteotomasini.com 2025"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"
useNetlifyForm = true
[params.address]
address = ""
email = "matteo.tomasini@gmail.com"
openingHours = ""
phone = ""
[params.map]
APIkey = ""
latitude = ""
longitude = ""
pinImage = ""
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/mattetom"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/matteotomasini"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/MatteoTomasini7"
weight = 3